# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

### Strategy for the solution:

**Apply the cleaning function to the new combined dataset:**
- load the three raw CSV files
- merge them,
- cleaning the large dataset

In [160]:
# Your code goes here

import numpy as np
import pandas as pd

df1 = pd.read_csv(
    'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'
)
df2 = pd.read_csv(
    'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv'
)
df3 = pd.read_csv(
    'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv'
)

In [161]:
print("Shape of dataframes:")
display(f"Shape df1: {df1.shape}")
display(f"Shape df2: {df2.shape}")
display(f"Shape df3: {df3.shape}")


print("\nInfo about dataframes:")

display(f"Info df1: {df1.info()}")
display(f"Info df2: {df2.info()}")
display(f"Info df3: {df3.info()}")

Shape of dataframes:

'Shape df1: (4008, 11)'

'Shape df2: (996, 11)'

'Shape df3: (7070, 11)'

Info about dataframes:
<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 417.4 KB

'Info df1: None'

<class 'pandas.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    str
 1   ST                         996 non-null    str
 2   GENDER                     991 non-null    str
 3   Education                  996 non-null    str
 4   Customer Lifetime Value    992 non-null    str
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    str
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    str
 10  Vehicle Class              996 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 150.6 KB

'Info df2: None'

<class 'pandas.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   str
 1   State                      7070 non-null   str
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   str
 4   Gender                     7070 non-null   str
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   str
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 957.0 KB

'Info df3: None'

In [162]:
# Dealing with the column names:

for df in [df1, df2, df3]:
  df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

df1 = df1.rename(columns={'st': 'state'})
df2 = df2.rename(columns={'st': 'state'})
# in df3 the column name is state originally

In [163]:
# Combine the 3 dataframe since the names of the columns are the same
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

print("\nColumns of combined df:", combined_df.columns.tolist())
print("\n")
display(f"Shape of combined df: {combined_df.shape}")
print("\n")
display(f"Info of combined df: {combined_df.info()}")

Columns of combined df: ['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

'Shape of combined df: (12074, 11)'

<class 'pandas.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   str
 1   state                      9137 non-null   str
 2   gender                     9015 non-null   str
 3   education                  9137 non-null   str
 4   customer_lifetime_value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   str
 9   vehicle_class              9137 non-null   str
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(3), object(2), str(6)
memory usage: 1.5+ MB

'Info of combined df: None'

In [164]:
# ---------------------------------------------------------
# 4. Customer Lifetime Value (CLV) cleaning
# ---------------------------------------------------------

print('\n--- CLV Cleaning & Verification ---')
print('Raw CLV null count:', combined_df['customer_lifetime_value'].isna().sum())

combined_df['customer_lifetime_value'] = (
    combined_df['customer_lifetime_value']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace('$', '', regex=False)
    .str.strip()
)

combined_df['customer_lifetime_value'] = pd.to_numeric(
    combined_df['customer_lifetime_value'], errors='coerce'
)

# SAMPLE CHECK 
print(
    'CLV Null count after numeric conversion:',
    combined_df['customer_lifetime_value'].isna().sum(),
)
print('Converted CLV Sample (head):')
print(combined_df['customer_lifetime_value'].head())

Raw CLV nulls: 2944
CLV nulls after clean numeric conversion: 2944

In [165]:
# number_of_open_complaints - cleaning and convert to integer
def parse_complaints(val):
  if pd.isna(val) or val is None or str(val).strip().lower() in ['nan', 'none']:
    return np.nan

  val_str = str(val).strip()

  if '/' in val_str:
    parts = val_str.split('/')
    if len(parts) > 1 and parts[1].strip().isdigit():
      return int(parts[1].strip())
    elif parts[0].strip().isdigit():
      return int(parts[0].strip())

  try:
    return int(float(val_str))
  except (ValueError, TypeError):
    return np.nan


combined_df['number_of_open_complaints'] = combined_df[
    'number_of_open_complaints'
].apply(parse_complaints)

combined_df['number_of_open_complaints'] = (
    combined_df['number_of_open_complaints'].fillna(0).astype(int)
)

In [166]:
# 3. Standardization of categories (Gender, State, Education)
# print(combined_df['vehicle_class'].unique())


# [nan, 'F', 'M', 'Femal', 'Male', 'female']
# ['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',       'Cali',         'AZ',         'WA',          nan]
# [              'Master',             'Bachelor', 'High School or Below','College','Bachelors','Doctor', nan]
# ['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV','Sports Car',    'Luxury Car']


# Gender - and insert U, as unkonwn if we have missing data
# I'm not delete these lines because the insured event, the claim, still exists.

combined_df['gender'] = combined_df['gender'].replace({
     'Femal': 'F',
     'female': 'F',
     'Male': 'M',
})



combined_df['state'] = combined_df['state'].replace(
     {'AZ': 'Arizona', 'Cali': 'California', 'WA': 'Washington'}
)

combined_df['education'] = combined_df['education'].replace(
     {'Bachelors': 'Bachelor'}
 )
print(combined_df['gender'].unique())
print(combined_df['state'].unique())
print(combined_df['education'].unique())

<ArrowStringArray>
[nan, 'F', 'M']
Length: 3, dtype: str
<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str
<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [145]:
# 5. Clean duplicated and empty rows and missing CLV values
shape_before_cleaning = combined_df.shape

combined_df = combined_df.dropna(how='all')

combined_df = combined_df.dropna(subset=['customer_lifetime_value'])
combined_df['customer_lifetime_value'] = combined_df[
    'customer_lifetime_value'
].round(2)

combined_df = combined_df.drop_duplicates().reset_index(drop=True)

shape_after_cleaning = combined_df.shape

Missing values in customer_lifetime_value were dropped rather than imputed because CLV is a critical target metric for customer valuation and financial summaries. Imputing CLV using standard measures like mean or median could introduce significant bias into future revenue and lifetime value calculations. Since the proportion of missing CLV rows is very small, dropping them ensures the analysis remains accurate without distorting financial metrics.

In [146]:
# 6. Round 2 the float64 types columns
target_columns = ['customer_lifetime_value', 'income', 'monthly_premium_auto', 'total_claim_amount']
combined_df[target_columns] = combined_df[target_columns].round(2)

display(combined_df)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.46
1,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.47
2,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.88
3,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.27
4,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,0,Personal Auto,Two-Door Car,159.38
...,...,...,...,...,...,...,...,...,...,...,...
9122,LA72316,California,M,Bachelor,23405.99,71941.0,73.0,0,Personal Auto,Four-Door Car,198.23
9123,PK87824,California,F,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.20
9124,TD14365,California,M,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.78
9125,UP19263,California,M,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.20
9126,Y167826,California,M,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.60

### Dealing with Null values

In [147]:
print("Missing values per column:")
print('\n')
print(combined_df.isnull().sum())

Missing values per column:


customer                       0
state                          0
gender                       120
education                      0
customer_lifetime_value        0
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

### Save the clean dataframes

In [148]:
# Final check:

print(f'Shape before row filtering/duplicates drop: {shape_before_cleaning}')
print(f'Final cleaned dataframe shape: {shape_after_cleaning}')
print(
    f'Total rows preserved: {shape_after_cleaning[0]} out of'
    f' {shape_before_cleaning[0]}'
)

Shape before row filtering/duplicates drop: (12074, 11)
Final cleaned dataframe shape: (9127, 11)
Total rows preserved: 9127 out of 12074

In [149]:
combined_df.to_csv('combined_df.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'combined_df.csv'")

The cleaned and formatted dataset saved:'combined_df.csv'

Data Cleaning Verification & Justification:
- Customer Lifetime Value (CLV): Before coercing to numeric, values were explicitly stripped of % formatting and whitespace. We printed null counts before and after numeric coercion to verify that no valid formatted rows were improperly converted to NaNs. Rows with missing CLV were only dropped after verifying that all recoverable formatting issues were addressed.

- Number of Open Complaints: The parsing function explicitly checks for slash-separated formats (x/y/z) and extracts the second segment (parts[1), which corresponds to the true complaint count in this dataset. Unformatted numeric values are preserved directly, avoiding false NaN coercions.

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [150]:
import numpy as np
import pandas as pd

url ="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv"
marketing = pd.read_csv(url)


marketing.shape
display(marketing)

marketing.info()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,1214.400000,Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.306996,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A,2
10909,10909,IV32877,California,6857.519928,No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,1021.719397,SUV,Medsize,A,1

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10910 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  str
 24  vehicle_size                   10910 non-null  str
 25  vehicle_type                   10910 non-null  str
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), str(17)
memory usage: 3.5 MB

### Column Names Operations

In [151]:
marketing.columns = (
    marketing.columns
    .str.strip()        
    .str.lower()        
    .str.replace(" ", "_")
    .str.replace(":", "")
    
)

marketing = marketing.rename(columns={
    "employmentstatus": "employment_status"
})


marketing = marketing.drop(columns=['unnamed_0'])
# The column named `unnamed:_0` is most likely an index left over from a previous save operation
# as it does not contain any new business-relevant information, I removed it

display(marketing.columns.tolist())

['customer',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employment_status',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

### Cleaning invalid values

In [152]:
display(marketing['effective_to_date'].unique())
display(marketing['effective_to_date'].nunique())

# round 2 decimal:
marketing['customer_lifetime_value'] = marketing['customer_lifetime_value'].round(2)
marketing['total_claim_amount'] = marketing['total_claim_amount'].round(2)

<ArrowStringArray>
['2011-02-18', '2011-01-18', '2011-02-10', '2011-01-11', '2011-01-17',
 '2011-02-14', '2011-02-24', '2011-01-19', '2011-01-04', '2011-01-02',
 '2011-02-07', '2011-01-31', '2011-01-26', '2011-02-28', '2011-01-16',
 '2011-02-26', '2011-02-23', '2011-01-15', '2011-02-02', '2011-02-15',
 '2011-01-24', '2011-02-21', '2011-02-22', '2011-01-07', '2011-01-28',
 '2011-02-08', '2011-02-12', '2011-02-20', '2011-01-05', '2011-02-19',
 '2011-01-03', '2011-02-03', '2011-01-22', '2011-01-23', '2011-02-05',
 '2011-02-13', '2011-01-25', '2011-02-16', '2011-02-01', '2011-01-27',
 '2011-01-12', '2011-01-20', '2011-02-06', '2011-02-11', '2011-01-21',
 '2011-01-29', '2011-01-09', '2011-02-09', '2011-02-27', '2011-01-01',
 '2011-02-17', '2011-02-25', '2011-01-13', '2011-01-06', '2011-02-04',
 '2011-01-14', '2011-01-10', '2011-01-08', '2011-01-30']
Length: 59, dtype: str

59

### Dtype operations

In [153]:
marketing['months_since_last_claim'] = marketing['months_since_last_claim'].astype(int)
marketing['number_of_open_complaints'] = marketing['number_of_open_complaints'].astype(int)
marketing['effective_to_date'] = pd.to_datetime(marketing['effective_to_date'])
# now the format is: 2011-01-30 00:00:00, but I do not want to make more modification, 
# since as I understand if I make more modification (slice, forexample) it can be cause problems
# and this format does not effect the analyzation of data 

print(marketing.dtypes)

customer                                    str
state                                       str
customer_lifetime_value                 float64
response                                    str
coverage                                    str
education                                   str
effective_to_date                datetime64[us]
employment_status                           str
gender                                      str
income                                    int64
location_code                               str
marital_status                              str
monthly_premium_auto                      int64
months_since_last_claim                   int64
months_since_policy_inception             int64
number_of_open_complaints                 int64
number_of_policies                        int64
policy_type                                 str
policy                                      str
renew_offer_type                            str
sales_channel                               str
total_claim_amount                      float64
vehicle_class                               str
vehicle_size                                str
vehicle_type                                str
month                                     int64
dtype: object

### Null Values

In [154]:
print("Missing values per column:")
print(marketing.isnull().sum())

# since everywhere is 0, no action needed

Missing values per column:
customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employment_status                0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

### Duplicates

In [155]:
duplicates_count = marketing.duplicated().sum()
print(f"Number of duplicated rows before cleaning: {duplicates_count}")

Number of duplicated rows before cleaning: 460

In [156]:
# Number of duplicated rows before cleaning: 460

marketing = marketing.drop_duplicates(keep='first').reset_index(drop=True)
duplicates_count = marketing.duplicated().sum()
print(f"Number of duplicated rows after cleaning: {duplicates_count}")

Number of duplicated rows after cleaning: 0

In [157]:
marketing.to_csv('marketing_cleaned_data.csv', index=False)
print("\nThe cleaned and formatted dataset saved:'marketing_cleaned_data.csv'")

The cleaned and formatted dataset saved:'marketing_cleaned_data.csv'

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [158]:
# 1. Pivot table for total revenue by sales channel


revenue_by_channel = (
    marketing.pivot_table(
        index='sales_channel', values='customer_lifetime_value', aggfunc='sum'
    )
    .sort_values(by='customer_lifetime_value', ascending=False)
    .round(2)
)


revenue_by_channel.columns = ['total_revenue']

print('Revenue by sales channels:\n')

display(revenue_by_channel)

Revenue by sales channels:

               total_revenue
sales_channel
Agent            31723779.87
Branch           23507902.38
Call Center      16523198.73
Web              12106815.13

### Revenue by sales channels

* Dominance of Agent Channel: The Agent channel generates the highest revenue amount by far (over 31,7 million), indicating that personalized, human-driven sales and customer management handle the largest volume of high-value policies or claims.

* Traditional vs. Digital Channels: Traditional offline channels (Agent and Branch) account for the vast majority of the total claim amounts, significantly outperforming remote and digital touchpoints.

* Lower Digital Engagement: The Web channel records the lowest total claim amount (~12 million), suggesting lower customer adoption, smaller policy sizes, or simpler products being processed online compared to traditional methods.

* Strategic Recommendation: Management should investigate ways to boost digital channel adoption (Web) to capture more online market share, while ensuring continued support for the high-performing Agent and Branch networks.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [159]:
# 2. Pivot Table: Average Customer Lifetime Value by Gender and Education Level
print('Average Customer Lifetime Value by Gender and Education Level:\n')

clv_multi_index = (
    marketing.pivot_table(
        index=['gender', 'education'],
        values='customer_lifetime_value',
        aggfunc='mean',
    )
    .round(2)
)

display(clv_multi_index)

Average Customer Lifetime Value by Gender and Education Level:

                             customer_lifetime_value
gender education
F      Bachelor                              7913.29
       College                               7757.32
       Doctor                                7369.59
       High School or Below                  8617.79
       Master                                8224.62
M      Bachelor                              7698.64
       College                               8075.26
       Doctor                                7414.86
       High School or Below                  8159.38
       Master                                8154.61

### Average Customer Lifetime Value (CLV) by Gender and Education Level

Most Valuable Segment (Secondary Education):
- Women with a "High School or Below" education level have the highest average customer lifetime value (8,617.79 USD).
- Men in this category also show a high average (8,159.38 USD); consequently, this education level represents the most valuable customer segment for the insurance company overall.

Higher Education (Master’s & College):
- For individuals with a Master’s (MSc) degree, the CLV is balanced and above average for both genders (~8,200 USD).
- In the "College" category, men exhibit a notably higher value (8,075.26 USD) compared to women (7,757.32 USD).

Lowest Customer Lifetime Value (Doctoral Degree):
- Customers with a doctoral (PhD) degree have the lowest average CLV across both genders (~7,370 – 7,415 USD).

Gender differences:
- The disparity between genders is minimal (with a difference of 1–4% in most categories). Educational attainment is a significantly stronger indicator than gender when estimating customer value.


### Insight: 
The pivot table reveals that it is not those with the highest level of education (Doctorate) who generate the highest Customer Lifetime Value, but rather customers with a secondary education (High School or Below). Since the difference between genders is negligible, it is more effective to focus on educational attainment and income segments—rather than gender—when targeting marketing campaigns.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [26]:
# Your code goes here